server:
  port: 8800
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: GEfSuDyTeu7MvZyc
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      #Redis服务器地址
      host: localhost
      #Redis服务器连接端口
      port: 6379
      #Redis如果有密码,需要配置, 没有密码就不要写
      password: 123456
      #Redis数据库索引（默认为0）
      database: 0
      #连接超时时间（毫秒）
      timeout: 1800000
      jedis:
        pool:
          #连接池最大连接数（使用负值表示没有限制）
          max-active: 20
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
          #连接池中的最大空闲连接
          max-idle: 5
          #连接池中的最小空闲连接
          min-idle: 0
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
